#ifndef _SHADER_INCLUDE_H_
#define _SHADER_INCLUDE_H_

#define MAX_DESCRIPTORS                100

#define RESOURCE_DESCRIPTOR_TYPE_COUNT 7
#define RESOURCE_HEAP_SIZE             MAX_DESCRIPTORS * RESOURCE_DESCRIPTOR_TYPE_COUNT

#define SAMPLER_DESCRIPTOR_TYPE_COUNT 1
#define SAMPLER_HEAP_SIZE             MAX_DESCRIPTORS * SAMPLER_DESCRIPTOR_TYPE_COUNT

#endif
